#define ATTRIB_LOCATION_POSITION 0
#define ATTRIB_LOCATION_NORMAL 1
#define ATTRIB_LOCATION_COLOR 2
#define ATTRIB_LOCATION_UV 3

#define UNIFORM_LOCATION_MODEL_MATRIX 0
#define UNIFORM_LOCATION_VIEW_MATRIX 1
#define UNIFORM_LOCATION_PROJECTION_MATRIX 2
#define UNIFORM_LOCATION_COLOR_TEXTURE_1 3
#define UNIFORM_LOCATION_COLOR_TEXTURE_2 4
#define UNIFORM_LOCATION_NORMAL_TEXTURE 5
#define UNIFORM_LOCATION_Z_TEXTURE 6
